language: cpp

compiler: gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake qt4-dev-tools
- sudo pip install cpp-coveralls --use-mirrors

before_script:
 - mkdir build
 - cd build
 - cmake ../deps/qjson
 - cmake ..

after_success:
  - coveralls --exclude bin --exclude deps --exclude doc --exclude var
  
script: make

notifications:
 email:
   - kcris@sogetthis.com
 on_success: change
 on_failure: always
