language: cpp

compiler: gcc

before_install:
- cat /etc/issue
- apt-cache search qt5
- sudo apt-get update -qq
- sudo apt-get install -qq cmake qt4-dev-tools
- sudo pip install cpp-coveralls --use-mirrors

before_script:
 - cd deps/qjson
 - cmake .
 - make
 - cd ..
 - mkdir build
 - cd build
 - cmake ..

after_success:
  - coveralls --exclude bin --exclude deps --exclude doc --exclude var
  
script: make -f ../Makefile

notifications:
 email:
   - kcris@sogetthis.com
 on_success: change
 on_failure: always
